"""empty message

Revision ID: 664435f70f53
Revises: febc2c08fa26
Create Date: 2024-03-14 00:38:47.806089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664435f70f53'
down_revision = 'febc2c08fa26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('saved_recipe_ids', sa.String(), nullable=True))

    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('recipe_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('feedback',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.alter_column('feedback',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('recipe_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('saved_recipe_ids')
        batch_op.drop_column('allergies')
        batch_op.drop_column('diet')

    # ### end Alembic commands ###
